version: "3.3"

services:
  database:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wakadb
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
